[package]
name = "raycaster"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.3.25"
macroquad-profiler = "0.1.1"

[profile.dev.package.'*']
opt-level = 3

[profile.release]
opt-level = 3
